org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.daemon.idletimeout=600
systemProp.net.minecraftforge.gradle.check.certs=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=dreamingfishcore
mod_name=DreamingfishCore
mod_license=GPL-3.0
mod_version=0.3
mod_group_id=com.hhy.dreamingfishcore
mod_authors=QingMo, HanHanYu
mod_description=A Minecraft DreamingFish core RPG systems mod.

geckolib_version=4.8.2
jei_version=15.20.0.127
